routes/web.php
<?php

use App\Models\Conference;
use App\Models\Portal;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;
use App\Models\User;

require __DIR__.'/auth.php';

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware(['auth'])->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect('/');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();

    return back()->with('status', 'verification-link-sent');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

/*
    ===================================================================
*/

View::composer(['*'], function ($view) {
    $portal = Portal::firstPortal(0);
    $conference = Conference::getConferenceTanggalPentingByPortal($portal->id);

    View::share('abc', $conference);
    View::share('logo', $portal->portal_logo);

    if (Auth::user()) {
        $user = User::firstUserDataUser(Auth::user()->id);
        View::share('roles', $user['roles']);
    }
});
// Route::get('data/abc12345/{id}', function($id) {
//     User::whereId($id)->update([
//         'password'  => Hash::make('12345678'),
//     ]);
// });

/*
    ===================================================================
*/

Route::namespace('App\Http\Controllers')->middleware('auth', 'verified')->group(function () {
    // Pengaturan
    Route::get('pengaturan', 'PengaturanController@index')->name('pengaturan.index');
    Route::put('pengaturan/biodata/{id}', 'PengaturanController@biodata')->name('pengaturan.biodata');
    Route::put('pengaturan/password/{id}', 'PengaturanController@password')->name('pengaturan.password');

    // Admin
    Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('role:admin')->group(function () {
        // Master
        Route::namespace('Master')->prefix('master')->name('master.')->group(function () {
            // Data Kewarganegaraan
            Route::resource('kewarganegaraan', 'KewarganegaraanController');
            Route::get('data/kewarganegaraan', 'KewarganegaraanController@data')->name('kewarganegaraan.data');

            // Data User
            Route::resource('user', 'UserController');
            Route::get('data/user', 'UserController@data')->name('user.data');
            Route::post('data/user/{action}/{user}', 'UserController@action')->name('user.action');
            Route::post('verified/user/{id}', 'UserController@verified')->name('user.verified');

            // Data Author
            Route::get('author', 'UserController@author')->name('author.index');

            // Data Reviewer
            // Route::get('reviewer', 'UserController@reviewer')->name('reviewer.index');

            // Data FAQ
            Route::resource('faq', 'FAQController');
            Route::get('data/faq', 'FAQController@data')->name('faq.data');

            // Data Portal
            Route::resource('portal', 'PortalController');
            Route::get('data/portal', 'PortalController@data')->name('portal.data');
            Route::get('data/portal/trashed', 'PortalController@dataTrashed')->name('portal.data_trashed');

            // Data Conference
            Route::resource('conference', 'ConferenceController');
            Route::get('data/conference', 'ConferenceController@data')->name('conference.data');

            // Data Publisher
            Route::resource('publisher', 'PublisherController');
            Route::get('data/publisher', 'PublisherController@data')->name('publisher.data');
        });
    });
    Route::namespace('AdminConference')->prefix('admin-conference')->name('admin-conference.')->middleware('role:admin_conference')->group(function () {
        Route::get('/', 'HomeController@index')->name('home');
        // Conference
        Route::namespace('Conference')->prefix('conference')->name('conference.')->group(function () {
            // Data Conference
            Route::resource('conference', 'ConferenceController');
            Route::get('data/conference', 'ConferenceController@data')->name('conference.data');
            Route::get('tanggal/conference/{id}', 'ConferenceController@tanggal')->name('conference.tanggal');
            Route::get('publisher/conference/{id}', 'ConferenceController@publisher')->name('conference.publisher');
            Route::get('publishers/conference/{id}', 'ConferenceController@publishers')->name('conference.publishers');

            // Data Topik
            Route::resource('topik', 'TopikController');
            Route::get('data/topik', 'TopikController@data')->name('topik.data');

            // Data Keynote Speaker
            Route::resource('keynote', 'KeynoteSpeakerController');
            Route::get('data/keynote', 'KeynoteSpeakerController@data')->name('keynote.data');

            // Data Pengumuman
            Route::resource('pengumuman', 'PengumumanController');
            Route::get('data/pengumuman', 'PengumumanController@data')->name('pengumuman.data');

            // Data Sponsor
            Route::resource('sponsor', 'SponsorController');
            Route::get('data/sponsor', 'SponsorController@data')->name('sponsor.data');

            // Data Voucher
            Route::resource('voucher', 'VoucherController');
            Route::get('data/voucher', 'VoucherController@data')->name('voucher.data');

            // Data Tanggal Penting
            Route::resource('tanggal-penting', 'TanggalPentingController');
            Route::get('data/tanggal-penting', 'TanggalPentingController@data')->name('tanggal-penting.data');

            // Data Organizer
            Route::resource('organizer', 'OrganizerController');

            // Data Halaman Statis
            Route::resource('page', 'PageController');
            Route::get('data/page', 'PageController@data')->name('page.data');

            // LOA
            Route::resource('loa', 'LoaController');
            Route::put('loa/gambar/{loa}', 'LoaController@gambar')->name('loa.gambar');
        });

        // Submission
        Route::namespace('Submission')->prefix('submission')->name('submission.')->group(function () {
            // Data Pembayaran Submission
            Route::get('pembayaran', 'PembayaranController@index')->name('pembayaran.index');
            Route::get('pembayaran/{id}', 'PembayaranController@show')->name('pembayaran.show');
            Route::put('pembayaran/{id}', 'PembayaranController@update')->name('pembayaran.update');
            Route::get('data/pembayaran', 'PembayaranController@data')->name('pembayaran.data');

            // Data Review Submission
            Route::get('review', 'ReviewController@index')->name('review.index');
            Route::get('data/review', 'ReviewController@data')->name('review.data');
            Route::get('riwayat-data/review', 'ReviewController@riwayatdata')->name('review.riwayat-data');
            Route::put('review/review/{id}', 'ReviewController@review')->name('review.review');
            Route::put('review/validasi/{id}', 'ReviewController@validasi')->name('review.validasi');
            Route::get('review/{id}', 'ReviewController@show')->name('review.show');

            // Data Book of Abstract
            Route::get('abstract', 'AbstractController@index')->name('abstract.index');
            Route::get('data/abstract', 'AbstractController@data')->name('abstract.data');
            Route::get('abstract/{id}', 'AbstractController@show')->name('abstract.show');

            // Data Full Paper
            Route::get('full-paper', 'AbstractController@fullpaper')->name('abstract.full-paper');
            Route::get('data/full-paper', 'AbstractController@fullpaperdata')->name('abstract.full-paper.data');
        });

        // Laporan
        Route::prefix('laporan')->name('laporan.')->group(function () {
            // Data Laporan Peserta Conference
            Route::get('peserta-conference', 'LaporanController@peserta_index')->name('peserta.index');
            Route::get('peserta-conference/data/{submission}', 'LaporanController@peserta_detail')->name('peserta.detail');
            Route::get('peserta-conference/{id}', 'LaporanController@peserta_show')->name('peserta.show');

            // Data Laporan Pembayaran
            Route::get('pembayaran', 'LaporanController@pembayaran_index')->name('pembayaran.index');
            Route::get('pembayaran/data/{submission}', 'LaporanController@pembayaran_show')->name('pembayaran.show');
        });

        // Publication
        Route::namespace('Publication')->prefix('publication')->name('publication.')->group(function () {
            // Proceeding
            Route::prefix('proceeding')->name('proceeding.')->group(function () {
                Route::get('dropdown', 'ProceedingController@dropdown')->name('dropdown');
            });
            Route::resource('proceeding', 'ProceedingController');
            
            // Proceeding
            Route::prefix('proceeding-detail')->name('proceeding-detail.')->group(function () {
                Route::get('submission/{proceeding}', 'ProceedingDetailController@submission')->name('submission');
            });
            Route::resource('proceeding-detail', 'ProceedingDetailController');

            // Submission
            Route::prefix('submission')->name('submission.')->group(function () {
                Route::get('author/{submission}', 'SubmissionController@show_author')->name('show_author');
                Route::get('users', 'SubmissionController@users')->name('users');
                Route::get('{submission}', 'SubmissionController@show')->name('show');

app/Models/FAQ.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;

class FAQ extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'faq';
    protected $fillable = ['faq_pertanyaan', 'faq_jawaban'];

    static function storeFAQ($request)
    {
        FAQ::create([
            'faq_pertanyaan'    => $request->pertanyaan,
            'faq_jawaban'       => $request->jawaban
        ]);
    }

    static function updateFAQ($id, $request)
    {
        FAQ::whereId($id)->update([
            'faq_pertanyaan'    => $request->pertanyaan,
            'faq_jawaban'       => $request->jawaban
        ]);
    }

    static function deleteFAQ($id)
    {
        FAQ::whereId($id)->delete();
    }

    static function getAll()
    {
        return FAQ::select('id', 'faq_pertanyaan as pertanyaan', 'faq_jawaban as jawaban')->get();
    }
}

app/Http/Controllers/Admin/Master/ConferenceController.php
<?php

namespace App\Http\Controllers\Admin\Master;

use App\Http\Controllers\Controller;
use App\Models\Conference;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;

use Yajra\DataTables\Facades\DataTables;
use App\Models\Portal;
use App\Models\User;
use App\Models\TanggalPenting;
use App\Models\Loa;
use Str;

class ConferenceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $portal = Portal::getPortalIdNama();
        $admin = User::getUserByRole(2);

        return view('pages.admin.master.conference', compact('portal', 'admin'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $conference = Conference::storeConference($request, Str::slug($request->nama).'-'.Str::random(3));

        Loa::create([
            'conference_id' => $conference->id
        ]);

        $this->storeTanggalPenting($conference->id, $request->tanggal);
        
        return $this->status(1, 'Conference berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Conference  $conference
     * @return \Illuminate\Http\Response
     */
    public function show(Conference $conference)
    {
        return json_encode(Conference::singleConferenceTanggalPenting($conference->id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Conference  $conference
     * @return \Illuminate\Http\Response
     */
    public function edit(Conference $conference)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Conference  $conference
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Conference $conference)
    {
        Conference::updateAdminConference($conference->id, $request);
        
        $this->storeTanggalPenting($conference->id, $request->tanggal);
        
        return $this->status(1, 'Conference berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Conference  $conference
     * @return \Illuminate\Http\Response
     */
    public function destroy(Conference $conference)
    {
        Conference::deleteConference($conference->id);
        
        return $this->status(1, 'Conference berhasil dihapus');
    }

    public function data()
    {
        $conference = Conference::join('users', 'conference.user_id', 'users.id')
                        ->join('portal', 'conference.portal_id', 'portal.id')
                        ->select(['conference.id', 'conference.conference_nama', 'users.name', 'portal.portal_nama', 'conference.conference_status']);
        
        return DataTables::of($conference)
            ->addColumn('status', function ($item) {
                if (App::isLocale('en')) {
                    if ($item->conference_status == 1) {
                        return '<div disabled class="badge badge-md badge-success">Active</div>';
                    } else if ($item->conference_status == 2) {
                        return '<div disabled class="badge badge-md badge-warning">Draft</div>';
                    } else {
                        return '<div disabled class="badge badge-md badge-danger">Inactive</div>';
                    }
                } else {
                    if ($item->conference_status == 1) {
                        return '<div disabled class="badge badge-md badge-success">Aktif</div>';
                    } else if ($item->conference_status == 2) {
                        return '<div disabled class="badge badge-md badge-warning">Draf</div>';
                    } else {
                        return '<div disabled class="badge badge-md badge-danger">Tidak Aktif</div>';
                    }
                }
            })
            ->addColumn('aksi', function ($item) {
                return '<form class="text-center" method="POST"><div class="btn-group"><button type="button" class="btn btn-warning ubah" data-value="'. $item->id .'"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></button><button type="button" class="btn btn-danger hapus" onclick="hapus('. $item->id .')"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg></button></div></form>';
            })
            ->rawColumns(['status', 'aksi'])
            ->removeColumn('conference_status', 'id')
            ->make(true);
    }

    public function status($id, $keterangan)
    {
        if ($id == 1) {
            $status = 'Berhasil';
        } else {
            $status = 'Gagal';
        }

        return [
            'id'            => $id,
            'status'        => $status,
            'keterangan'    => $keterangan
        ];
    }

    public function storeTanggalPenting($id, $tanggal)
    {
        TanggalPenting::deleteTanggalPentingByConference($id);
        
        TanggalPenting::storeTanggalPentingDefault($id, "Upload Abstrak", date('Y-m-d', strtotime($tanggal . "- 2 days")), 0);
        TanggalPenting::storeTanggalPentingDefault($id, "Pembayaran", date('Y-m-d', strtotime($tanggal . "- 1 days")), 0);
        TanggalPenting::storeTanggalPentingDefault($id, "Conference", $tanggal, 1);
        TanggalPenting::storeTanggalPentingDefault($id, "Upload Full Paper", date('Y-m-d', strtotime($tanggal . "+ 1 days")), 0);
        TanggalPenting::storeTanggalPentingDefault($id, "Review", date('Y-m-d', strtotime($tanggal . "+ 2 days")), 0);
        TanggalPenting::storeTanggalPentingDefault($id, "Pembayaran Publish", date('Y-m-d', strtotime($tanggal . "+ 3 days")), 0);
        TanggalPenting::storeTanggalPentingDefault($id, "Publish Artikel", date('Y-m-d', strtotime($tanggal . "+ 4 days")), 0);
    }
}

resources/views/pages/admin-conference/conference/page.blade.php
@extends('layout.layout')

@section('title', 'Data Halaman Statis')

@section('css')
	{{-- Datatables --}}
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/dataTables.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css') }}">

	{{-- Toastr --}}
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/toastr.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/ext-component-toastr.min.css') }}">

	{{-- SweetAlert --}}
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/sweetalert2.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/ext-component-sweet-alerts.min.css') }}">

	{{-- Summernote --}}
	<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
@endsection

@section('content')
	{{-- BEGIN: Datatable Button --}}
	<section>
        {{-- BEGIN: Table --}}
        <x-datatable-button title="Data Halaman Statis" id="tambah" buttonTitle='<i data-feather="plus"></i> Tambah'>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th data-priority="1">Judul</th>
                        <th>Conference</th>
                        <th data-priority="2" width="15%"></th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </x-datatable-button>
        {{-- END: Table --}}
		
		{{-- BEGIN: Modal --}}
		<x-modal title="Menunggu..." type="normal" class="modal-lg" id="modal">
			@if (count($conference) > 0)
				<form id="form" method="POST" enctype="multipart/form-data">
					@csrf

					<div class="modal-body">
						<x-form-group title="Judul (Maksimal 20 Karakter)">
							<input type="text" name="judul" class="form-control" placeholder="Judul Halaman Statis" required/>
						</x-form-group>

						<x-form-group title="Slug">
							<input type="text" name="slug" class="form-control" placeholder="Slug Halaman Statis" required/>
						</x-form-group>
						
						<x-form-group title="Conference">
							<select name="conference_id" class="form-control" required>
								<option value="" hidden>-- Pilih Conference --</option>

								@foreach ($conference as $item)
									<option value="{{ $item->id }}">{{ $item->nama }}</option>
								@endforeach
							</select>
						</x-form-group>
                        
                        <div id="gambar-old" class="mb-1"></div>

                        <x-form-group title="Gambar Baru">
                            <input type="file" name="gambar" accept="image/*" class="form-control-file">
                        </x-form-group>
						
						<x-form-group title="Isi">
							<textarea class="form-control" name="isi" rows="5" placeholder="Isi Halaman Statis"></textarea>
						</x-form-group>
					</div>

					<div class="modal-footer">
						<button type="submit" class="btn btn-primary mr-1" id="button-tambah"><i data-feather="check"></i> Simpan</button>
						<button type="reset" class="btn btn-outline-danger" id="button-batal" data-dismiss="modal"><i data-feather="x"></i> Batal</button>
					</div>
				</form>
			@else
				<x-kosong>Tidak ada Conference</x-kosong>
			@endif
		</x-modal>
		{{-- END: Modal --}}
		
		{{-- BEGIN: Delete --}}
        <form id="delete-form" method="POST">
            @csrf
            @method('DELETE')
        </form>
		{{-- END: Delete --}}
	</section>
	{{-- END: Datatable Button --}}
@endsection

@section('js')
	{{-- Datatable --}}
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.buttons.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/jszip.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/pdfmake.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/buttons.print.min.js') }}"></script>
	<script>
		var link = "{{ route('admin-conference.conference.page.data') }}";
		var column = [
			{data: 'judul', name: 'judul'},
			{data: 'conference_nama', name: 'conference.conference_nama'},
			{data: 'aksi', name: 'aksi', orderable: false, searchable: false}
		];
	</script>
	<script src="{{ asset('js/component/datatable-button.js') }}"></script>

	{{-- Summernote --}}
	<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
	<script>
		$('textarea[name="isi"]').summernote({
			height: 200,
			toolbar: [
				['style', ['style', 'bold', 'italic', 'underline']],
				['font', ['strikethrough', 'superscript', 'subscript']],
				['para', ['ul', 'ol', 'paragraph']],
				['fontsize', ['fontsize']],
			],
			styleTags: ['p','pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
		});
	</script>

	<script src="{{ asset('app-assets/vendors/js/extensions/toastr.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/extensions/sweetalert2.all.min.js') }}"></script>

    {{-- Modal --}}
	<script>
		$('#tambah').on('click', function() {
            $('.modal-title').text('Tambah Halaman Statis');
            $('#form').attr('action', "{{ route('admin-conference.conference.page.store') }}");

            $('#gambar-old').hide();

            $('#modal').modal('show');
        })

        function ubah(id) {
            $('.modal-title').text('Ubah Halaman Statis');
            $('#form').attr('action', `{{ url('admin-conference/conference/page/${id}') }}`);

            $('#form').append('<input type="hidden" name="_method" value="PUT">');
			
            $.get(`{{ url('admin-conference/conference/page/${id}') }}`, function( data ) {
				$('input[name="judul"]').val(data.judul);
                $('select[name="conference_id"]').val(data.conference_id);
                $('input[name="slug"]').val(data.slug);
				$('textarea[name="isi"]').summernote('pasteHTML', data.isi);
				
				if (data.gambar == null) {
					$('#gambar-old').hide();
				} else {
					$('#gambar-old').html(`
						<label>Gambar</label>
						<div class="text-center">
							<img src="/images/page/`+ data.gambar +`" class="img-fluid" />
						</div>
					`);
					$('#gambar-old').show();
				}

                $('#modal').modal('show');
            });
        }

        $('#modal').on('hidden.bs.modal', function () {
            $('.modal-title').text('');
            $('#form').attr('action', '');

            $('#form input[name="_method"]').remove();
            $('#form input[name!="_token"]').val('');
            $('#form select').val('');
			$('textarea[name="isi"]').summernote('reset');
        });
	</script>

    {{-- Form --}}
	<script type="text/javascript">
		$('form').submit(function(e) {
            e.preventDefault();

			$('form').find("button[type='submit']").prop('disabled', true);

            var formData = new FormData(this);

            $.ajax({
                url: $(this).attr('action'),
                type: "POST",
                data: formData,
                contentType: false,
                processData: false
            }).done(function(response){
                if (response.id == 1) {
                    $('#modal').modal('hide');
                }
                formExecuted(response);
            }).fail(function(response) {
                serverError(response.statusText, response.responseJSON.message, response.responseJSON.line);
            });
		});
	</script>

    {{-- Toastr --}}
    <script src="{{ asset('app-assets/vendors/js/extensions/toastr.min.js') }}"></script>
    <script>
        function formExecuted(response) {
			var status = '';

			if (response.id == 1) {
				status = 'success';
				table.ajax.reload();
				$('.modal').modal('hide');
			} else {
				status = 'error';
			}

			toastr[status](response.keterangan, response.status, {
				closeButton: true,
				tapToDismiss: true
			});

			$('form').find("button[type='submit']").prop('disabled', false);
		}

        function serverError(status, message, line) {
            toastr['error'](message, status +" on line "+ line, {
                closeButton: true,
                tapToDismiss: true
            });

            $('form').find("button[type='submit']").prop('disabled', false);
        }
    </script>

    {{-- SweetAlert --}}
	<script src="{{ asset('app-assets/vendors/js/extensions/sweetalert2.all.min.js') }}"></script>
	<script>
        // Hapus Data
		function hapus(id) {
            $('#delete-form').attr('action', `{{ url('admin-conference/conference/page/${id}') }}`);

			Swal.fire({
				title: 'Yakin ingin hapus?',
				icon: 'warning',
				showCancelButton: true,
				confirmButtonText: 'Ya',
				cancelButtonText: 'Tidak',
				customClass: {
					confirmButton: 'btn btn-primary',
					cancelButton: 'btn btn-outline-danger ml-1'
				},
				buttonsStyling: false
			}).then(function (result) {
				if (result.value) {
                    $('#delete-form').submit();
				}
			});
		}
    </script>
@endsection