routes/web.php
            Route::get('data/sponsor', 'SponsorController@data')->name('sponsor.data');

            // Data Voucher
            Route::resource('voucher', 'VoucherController');
            Route::get('data/voucher', 'VoucherController@data')->name('voucher.data');

            // Data Tanggal Penting
            Route::resource('tanggal-penting', 'TanggalPentingController');
            Route::get('data/tanggal-penting', 'TanggalPentingController@data')->name('tanggal-penting.data');

            // Data Organizer
            Route::resource('organizer', 'OrganizerController');

            // Data Halaman Statis
            Route::resource('page', 'PageController');
            Route::get('data/page', 'PageController@data')->name('page.data');

            // LOA
            Route::resource('loa', 'LoaController');
            Route::put('loa/gambar/{loa}', 'LoaController@gambar')->name('loa.gambar');
        });

        // Submission
        Route::namespace('Submission')->prefix('submission')->name('submission.')->group(function () {
            // Data Pembayaran Submission
            Route::get('pembayaran', 'PembayaranController@index')->name('pembayaran.index');
            Route::get('pembayaran/{id}', 'PembayaranController@show')->name('pembayaran.show');
            Route::put('pembayaran/{id}', 'PembayaranController@update')->name('pembayaran.update');
            Route::get('data/pembayaran', 'PembayaranController@data')->name('pembayaran.data');

            // Data Review Submission
            Route::get('review', 'ReviewController@index')->name('review.index');
            Route::get('data/review', 'ReviewController@data')->name('review.data');
            Route::get('riwayat-data/review', 'ReviewController@riwayatdata')->name('review.riwayat-data');
            Route::put('review/review/{id}', 'ReviewController@review')->name('review.review');
            Route::put('review/validasi/{id}', 'ReviewController@validasi')->name('review.validasi');
            Route::get('review/{id}', 'ReviewController@show')->name('review.show');

            // Data Book of Abstract
            Route::get('abstract', 'AbstractController@index')->name('abstract.index');
            Route::get('data/abstract', 'AbstractController@data')->name('abstract.data');
            Route::get('abstract/{id}', 'AbstractController@show')->name('abstract.show');

            // Data Full Paper
            Route::get('full-paper', 'AbstractController@fullpaper')->name('abstract.full-paper');
            Route::get('data/full-paper', 'AbstractController@fullpaperdata')->name('abstract.full-paper.data');
        });

        // Laporan
        Route::prefix('laporan')->name('laporan.')->group(function () {
            // Data Laporan Peserta Conference
            Route::get('peserta-conference', 'LaporanController@peserta_index')->name('peserta.index');
            Route::get('peserta-conference/data/{submission}', 'LaporanController@peserta_detail')->name('peserta.detail');
            Route::get('peserta-conference/{id}', 'LaporanController@peserta_show')->name('peserta.show');

            // Data Laporan Pembayaran
            Route::get('pembayaran', 'LaporanController@pembayaran_index')->name('pembayaran.index');
            Route::get('pembayaran/data/{submission}', 'LaporanController@pembayaran_show')->name('pembayaran.show');
        });

        // Publication
        Route::namespace('Publication')->prefix('publication')->name('publication.')->group(function () {
            // Proceeding
            Route::prefix('proceeding')->name('proceeding.')->group(function () {
                Route::get('dropdown', 'ProceedingController@dropdown')->name('dropdown');
            });
            Route::resource('proceeding', 'ProceedingController');
            
            // Proceeding
            Route::prefix('proceeding-detail')->name('proceeding-detail.')->group(function () {
                Route::get('submission/{proceeding}', 'ProceedingDetailController@submission')->name('submission');
            });
            Route::resource('proceeding-detail', 'ProceedingDetailController');

            // Submission
            Route::prefix('submission')->name('submission.')->group(function () {
                Route::get('author/{submission}', 'SubmissionController@show_author')->name('show_author');
                Route::get('users', 'SubmissionController@users')->name('users');
                Route::get('{submission}', 'SubmissionController@show')->name('show');
                Route::put('update-keyword/{submission}', 'SubmissionController@update_keyword')->name('update_keyword');
                Route::put('update-abstract/{submission}', 'SubmissionController@update_abstract')->name('update_abstract');
                Route::put('update-author/{submission}', 'SubmissionController@update_author')->name('update_author');
                Route::delete('delete-author/{submission}', 'SubmissionController@delete_author')->name('delete_author');
                Route::put('update-galley/{submission}', 'SubmissionController@update_galley')->name('update_galley');
            });
        });
    });
    Route::namespace('Author')->prefix('author')->name('author.')->middleware('role:author')->group(function () {
        // Data Profil
        Route::get('author/profil', 'HomeController@profil')->name('profil.index');

        // Author
        Route::namespace('Author')->prefix('author')->name('author.')->group(function () {
            // Data Daftar Conference
            Route::get('conference', 'ConferenceController@index')->name('conference.index');
            Route::get('data/conference', 'ConferenceController@data')->name('conference.data');
            Route::get('kewarganegaraan/conference', 'ConferenceController@kewarganegaraan')->name('conference.kewarganegaraan');
            Route::post('conference', 'ConferenceController@store')->name('conference.store');

            // Data Submission
            Route::get('submission', 'SubmissionController@index')->name('submission.index');
            Route::put('submission/{submission}', 'SubmissionController@update')->name('submission.update');
            Route::get('data/submission/{id}', 'SubmissionController@data')->name('submission.data');
            Route::get('submission/{id}', 'SubmissionController@show')->name('submission.show');
            Route::get('submission/{id}/loa', 'SubmissionController@loa')->name('submission.loa');
            Route::post('submission/{id}/{step}', 'SubmissionController@step')->name('submission.step');
            Route::delete('submission/{submission}', 'SubmissionController@destroy')->name('submission.destroy');

            // Data Publikasi
            Route::prefix('publication')->name('publication.')->group(function () {
                Route::get('author/{submission}', 'PublicationController@submission_show_author')->name('show_author');
                Route::get('users', 'PublicationController@submission_users')->name('users');
                Route::get('{submission}', 'PublicationController@submission_show')->name('show');
                Route::put('update-keyword/{submission}', 'PublicationController@submission_update_keyword')->name('update_keyword');
                Route::put('update-abstract/{submission}', 'PublicationController@submission_update_abstract')->name('update_abstract');
                Route::put('update-author/{submission}', 'PublicationController@submission_update_author')->name('update_author');
                Route::delete('delete-author/{submission}', 'PublicationController@submission_delete_author')->name('delete_author');
                Route::put('update-galley/{submission}', 'PublicationController@submission_update_galley')->name('update_galley');
            });
        });
    });
});

// Mockup Admin Conference Data Submission
Route::view('admin-conference/submission', 'pages.admin-conference.submission.submission');

// Mockup Admin Conference Data Laporan
Route::view('admin-conference/laporan/submission', 'pages.admin-conference.laporan.submission');
// Route::view('admin-conference/laporan/pembayaran', 'pages.admin-conference.laporan.pembayaran');
Route::view('admin-conference/laporan/published', 'pages.admin-conference.laporan.published');

// Mockup Author
Route::view('author', 'pages.author.home');
Route::view('author/book-of-abstract', 'pages.author.book-of-abstract');

/*
    ======================================== Front End ========================================
*/

//
Route::get('panel', 'App\Http\Controllers\HomeController@index')->middleware('auth', 'verified');
Route::post('role/{name}', 'App\Http\Controllers\HomeController@role')->middleware('auth', 'verified')->name('role');

Route::namespace('App\Http\Controllers\Front')->group(function () {
    Route::get('lang/{lang}', 'HomeController@lang')->name('lang');
    Route::name('portal.')->group(function () {
        Route::get('', 'HomeController@index')->name('home');
        Route::get('conferences', 'HomeController@conferences')->name('conferences');

        Route::prefix('announcements')->name('announcements.')->group(function () {
            Route::get('', 'HomeController@announcements')->name('index');
            Route::get('{pengumuman}', 'HomeController@announcements_show')->name('show');
        });
    });

    Route::prefix('{id}')->name('conference.')->group(function () {
        Route::get('', 'ConferenceController@index')->name('home');
        Route::get('register', 'ConferenceController@register')->name('register');
        Route::get('download', 'ConferenceController@download')->name('download');
        // Route::view('gallery', 'front.conference.gallery')->name('gallery');
        Route::get('schedule', 'ConferenceController@schedule')->name('schedule');
        Route::get('speaker', 'ConferenceController@speaker')->name('speaker');

        Route::prefix('page')->name('page.')->group(function () {

app/Models/FAQ.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;

class FAQ extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'faq';
    protected $fillable = ['faq_pertanyaan', 'faq_jawaban'];

    static function storeFAQ($request)
    {
        FAQ::create([
            'faq_pertanyaan'    => $request->pertanyaan,
            'faq_jawaban'       => $request->jawaban
        ]);
    }

    static function updateFAQ($id, $request)
    {
        FAQ::whereId($id)->update([
            'faq_pertanyaan'    => $request->pertanyaan,
            'faq_jawaban'       => $request->jawaban
        ]);
    }

    static function deleteFAQ($id)
    {
        FAQ::whereId($id)->delete();
    }

    static function getAll()
    {
        return FAQ::select('id', 'faq_pertanyaan as pertanyaan', 'faq_jawaban as jawaban')->get();
    }
}

app/Models/Proceeding.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Proceeding extends Model
{
    use HasFactory;

    public $fillable = ['conference_id', 'title', 'slug', 'editor', 'volume', 'issn', 'isbn', 'tanggal'];

    public function conference()
    {
        return $this->belongsTo(Conference::class, 'conference_id', 'id')->select('id', 'conference_nama as nama');
    }

    /**
     * The submissions that belong to the Proceeding
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function submissions()
    {
        return $this->belongsToMany(Submission::class, 'proceeding_details', 'proceeding_id', 'submission_id');
    }

    public function proceeding_details()
    {
        return $this->hasMany(ProceedingDetail::class, 'proceeding_id', 'id');
    }
}

app/Http/Controllers/AdminConference/Publication/ProceedingDetailController.php
<?php

namespace App\Http\Controllers\AdminConference\Publication;

// Laravel Framework Service Providers
use App\Http\Controllers\BaseController;
use Illuminate\Http\Request;

// Application Classes
use App\Models\Proceeding;
use App\Models\ProceedingDetail;
use App\Models\Submission;

// Package Service Providers
use Yajra\DataTables\Facades\DataTables;

class ProceedingDetailController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ProceedingDetail  $proceeding_detail
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Proceeding $proceeding_detail)
    {
        if ($request->ajax()) {
            $data = ProceedingDetail::query()
                ->orderBy('id', 'desc')
                ->where('proceeding_id', $proceeding_detail->id)
                ->with(['proceeding', 'submission'])
                ->get();

            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    return '<div class="btn-group"><button type="button" class="btn btn-danger btn-sm p-1" onclick="hapus('. $row->id .')" title="'. __("messages.delete") .'"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg></button><button type="button" class="btn btn-primary btn-sm p-1" onclick="detail('. $row->submission_id .')" title="'. __("messages.detail") .'"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></button></div>';
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ProceedingDetail  $proceeding_detail
     * @return \Illuminate\Http\Response
     */
    public function edit(ProceedingDetail $proceeding_detail)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ProceedingDetail  $proceeding_detail
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Proceeding $proceeding_detail)
    {
        if (ProceedingDetail::where('submission_id', $request->submission_id)->first() !== NULL) {
            ProceedingDetail::where('submission_id', $request->submission_id)->update([
                'proceeding_id' => $proceeding_detail->id,
                'submission_id' => $request->submission_id,
            ]);
        } else {
            $proceeding_detail = ProceedingDetail::create([
                'proceeding_id' => $proceeding_detail->id,
                'submission_id' => $request->submission_id,
                'kode'          => sprintf("%'08d", rand(1, 99999999))
            ]);
        }

        return $this->sendResponse($proceeding_detail, trans('messages.flash.created', ['data' => trans('messages.proceeding detail')]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ProceedingDetail  $proceeding_detail
     * @return \Illuminate\Http\Response
     */
    public function destroy(ProceedingDetail $proceeding_detail)
    {
        $proceeding_detail->delete();

        return $this->sendResponse([], trans('messages.flash.deleted', ['data' => trans('messages.proceeding detail')]));
    }

    public function submission(Request $request, Proceeding $proceeding)
    {
        if ($request->ajax()) {
            $data = Submission::query()
                ->select('submission.id', 'submission_judul')
                ->join('conference', 'submission.conference_id', 'conference.id')
                ->leftJoin('proceeding_details', 'submission.id', 'proceeding_details.submission_id')
                ->where('conference_id', $proceeding->conference_id)
                ->where('submission_status', 6)
                ->whereNull('proceeding_details.id')
                ->orderBy('proceeding_details.id')
                ->get();

            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    return '<button type="button" class="btn btn-success btn-sm px-50" onclick="tambah('. $row->id .')" title="'. __("messages.add") .'"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg></button>';
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }
}

resources/views/pages/admin-conference/publication/proceeding/index.blade.php
@extends('layout.layout')

@section('title')
{{ __('messages.proceeding') }}
@endsection

@section('vendor-css')
{{-- Datatables --}}
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/dataTables.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css') }}">

{{-- Toastr --}}
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/toastr.min.css') }}">

{{-- Select2 --}}
<link rel="stylesheet" type="text/css" href="{{ asset('/app-assets/vendors/css/forms/select/select2.min.css') }}">

{{-- SweetAlert --}}
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/sweetalert2.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/ext-component-sweet-alerts.min.css') }}">
@endsection

@section('css')
{{-- Toastr --}}
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/ext-component-toastr.min.css') }}">
@endsection

@section('content')
{{-- Tabel --}}
<div class="card">
    <div class="card-header border-bottom d-flex justify-content-between">
        <h6 class="card-title text-capitalize">{{ __('messages.data.proceeding') }}</h6>

        <button type="button" class="btn btn-primary" onclick="tambah()"><i data-feather="plus"></i> {{ __('messages.add') }}</button>
    </div>

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>No</th>
                    <th>{{ __('messages.title') }}</th>
                    <th>{{ __('messages.conference') }}</th>
                    <th>{{ __('messages.date') }}</th>
                    <th style="width: 12px"></th>
                </tr>
            </thead>
        </table>
    </div>
</div>

{{-- Modal --}}
<section>
    <div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <form id="form" action="{{ route('admin-conference.publication.proceeding.store') }}" method="POST">
                    @csrf
                    <input type="hidden" name="_method" value="post">

                    <div class="modal-body">
                        <div class="mb-1">
                            <label>{{ __('messages.title') }}</label>
                            <input type="text" name="title" class="form-control" required>
                        </div>

                        <div class="mb-1">
                            <label>{{ __('messages.slug') }}</label>
                            <input type="text" name="slug" class="form-control" required>
                        </div>

                        <div class="mb-1">
                            <label>{{ __('messages.conference') }}</label>
                            <select name="conference_id" class="form-control select2" required></select>
                        </div>

                        <div class="mb-1">
                            <label>{{ __('messages.editor') }}</label>
                            <textarea name="editor" class="form-control"></textarea>
                        </div>

                        <div class="mb-1">
                            <label>{{ __('messages.volume') }}</label>
                            <input type="text" name="volume" class="form-control">
                        </div>

                        <div class="mb-1">
                            <label>ISSN</label>
                            <input type="text" name="issn" class="form-control">
                        </div>

                        <div class="mb-1">
                            <label>ISBN</label>
                            <input type="text" name="isbn" class="form-control">
                        </div>

                        <div class="mb-1">
                            <label>{{ __('messages.date') }}</label>
                            <input type="date" name="tanggal" class="form-control" required>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">{{ __('messages.save') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <form method="post" id="form-proceeding">
        @csrf
        @method('DELETE')
    </form>
</section>
{{-- /Modal --}}
@endsection

@section('vendor-js')
{{-- Datatables --}}
<script src="{{ asset('app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>

{{-- Toastr --}}
<script src="{{ asset('app-assets/vendors/js/extensions/toastr.min.js') }}"></script>

{{-- Select2 --}}
<script src="{{ asset('/app-assets/vendors/js/forms/select/select2.full.min.js') }}"></script>

{{-- SweetAlert --}}
<script src="{{ asset('app-assets/vendors/js/extensions/sweetalert2.all.min.js') }}"></script>
@endsection

@section('js')
{{-- Datatables --}}
<script>
    var table = $('table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('admin-conference.publication.proceeding.index') }}",
        columns: [
            { data: 'DT_RowIndex', orderable: false, searchable: false },
            { data: 'title', name: 'title' },
            { data: 'conference.nama', name: 'conference.nama' },
            { data: 'tanggal', name: 'tanggal' },
            { data: 'action', name: 'action', orderable: false, searchable: false }
        ],
        dom: '<"d-flex justify-content-between align-items-center mx-1 row"<"col-sm-12 col-md-6"l><"col-sm-12 col-md-6"f>>t<"d-flex justify-content-between mx-1 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>',
    })
</script>

{{-- Toastr --}}
<script>
    function toastrStatus(icon, status, message, data) {
        toastr[icon](`<b>${message}</b><br>${data}`, status, {
            closeButton: true
        });

        $('form').find("button[type='submit']").prop('disabled', false);
    }
</script>

{{-- Select2 --}}
<script>
    $(`.select2`).select2({
        placeholder: "-- {{ __('messages.choose.conference') }}",
        width: '100%',
        ajax: {
            url: "{{ route('admin-conference.publication.proceeding.dropdown') }}",
            data: function (params) {
                var query = {
                    search: params.term,
                    page: params.page || 1
                }

                return query;
            }
        }
    })
</script>

{{-- SweetAlert --}}
<script>
    // Hapus Data
    function hapus(id) {
        $('#form-proceeding').attr("action", `{{ url('admin-conference/publication/proceeding/${id}') }}`)

        Swal.fire({
            title: 'Yakin ingin hapus?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Ya',
            cancelButtonText: 'Tidak',
            customClass: {
                confirmButton: 'btn btn-primary',
                cancelButton: 'btn btn-outline-danger ml-1'
            },
            buttonsStyling: false
        }).then(function (result) {
            if (result.value) {
                $('#form-proceeding').submit()
            }
        });
    }
</script>

{{-- Script --}}
<script>
    // Modal
    function tambah() {
        $('.modal input').not('.modal input[name="_token"]').val('')
        $('.modal select').children().remove()
        $('.modal textarea').val('')

        $('#form').attr('action', "{{ route('admin-conference.publication.proceeding.store') }}")
        $('.modal input[name="_method"]').val('POST')
        $('.modal-title').text("{{ __('messages.add') }} {{ __('messages.proceeding') }}")

        $('.modal').modal('show')
    }
    
    function ubah(id) {
        $('.modal select').children().remove()

        $('#form').attr('action', `{{ url('admin-conference/publication/proceeding/${id}') }}`)
        $('.modal-title').text("{{ __('messages.edit') }} {{ __('messages.proceeding') }}")
        $('.modal input[name="_method"]').val('PUT')

        $.get(`{{ url('admin-conference/publication/proceeding/${id}/edit') }}`, function(data) {
            $('.modal input[name="title"]').val(data?.data?.title)
            $('.modal input[name="slug"]').val(data?.data?.slug)
            $('.modal select[name="conference_id"]').html(`<option value="${data?.data?.conference.id}">${data?.data?.conference.nama}</option>`)
            $('.modal textarea[name="editor"]').val(data?.data?.editor)
            $('.modal input[name="volume"]').val(data?.data?.volume)
            $('.modal input[name="issn"]').val(data?.data?.issn)
            $('.modal input[name="isbn"]').val(data?.data?.isbn)            
            $('.modal input[name="tanggal"]').val(data?.data?.tanggal)
        })

        $('.modal').modal('show')
    }

    $('.modal').on('shown.bs.modal', function () {
        $('input[name="title"]').focus()
    })
    // /Modal

    // Form
    $('form').on('submit', function (e) {
        e.preventDefault()
        $('form').find("button[type='submit']").prop('disabled', true)
        var formData = new FormData(this)

        $.ajax({
            url: $(this).attr('action'),
            type: "POST",
            data: formData,
            contentType: false,
            processData: false
        }).done(function(response) {
            toastrStatus('success', `{{ __('messages.success') }}`, response.message, "")
            table.ajax.reload()
            $('#modal').modal('hide')
            response.data.id && detail(response.data.id)
        }).fail(function(response) {
            toastrStatus('error', `{{ __('messages.failed') }}`, response.responseJSON.message, response.responseJSON.data)
        })
    })

    // Redirect
    function detail(id) {
        window.location.href = `{{ url('admin-conference/publication/proceeding/${id}') }}`
    }
</script>
@endsection